### ISSUE TITLE
RNCNetInfo.getCurrentState got 3 arguments, expected 2. 

### ISSUE THREAD

**Issue by SanjanaTailor** [bugsnag/bugsnag-js#719]
Enviornment info :
System:
OS: Windows 10 10.0.17763
CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Memory: 1.06 GB / 7.88 GB
Binaries:
Node: 8.16.1 - C:\Program Files\nodejs\node.EXE
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
SDKs:
Android SDK:
API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
Build Tools: 26.0.2, 28.0.3, 29.0.2
System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
IDEs:
Android Studio: Version 3.5.0.0 AI-191.8026.42.35.6010548
npmPackages:
react: ~16.9.0 => 16.9.0
react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4

Facing this problem using expo directory.
import {AppState } from 'react-native';
import NetInfo from '@react-native-community/netinfo';

Using this two library

**Comment by mattdyoung** [comment]
Hi @SanjanaTailor 

It's not clear whether the error you're seeing is due to Bugsnag's use of NetInfo or your own.

It looks similar to this report, which sounds like it was misuse of the library:
https://github.com/expo/expo/issues/6837

If you believe this to be a bug in bugsnag-js can you provide a reproduction example?

**Comment by SanjanaTailor** [comment]
Hi @mattdyoung : 
Installed this expo library and getting this error 

import React, { Component } from 'react';
import { StyleSheet, View, Text, TouchableOpacity, Alert, FlatList, AppState } from 'react-native';
import NetInfo from '@react-native-community/netinfo';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      dataSource: "",
      appState: AppState.currentState
    }
  }

  FlatListItemSeparator = () => {
    return (
      <View style={{ height: 1.5, width: '100%', backgroundColor: '#dc143c' }} />
    );
  }

  gotoFetch = () => {
    NetInfo.fetch().then(state => {
      if (state.type == "none") {
        Alert.alert(
          'CONNECTIVITY ISSUE...',
          'Please check your Network Connectivity',
          [
            {
              text: 'Okay',
            }
          ]);
      } else {
        Alert.alert(
          'API Fetched',
          'To see fetched data go to ==>  /storage/emulated/0/test.txt',
          [
            {
              text: 'Okay',
            }
          ]);

        fetch('https://movies.json')
          .then((response) => response.json())
          .then((responseJson) => {
            console.log(responseJson)
            setTimeout(() => {
              this.setState({
                dataSource: responseJson.movies,
              });
            }, 2000;
  }

  render() {
    return (
      <View>

        <TouchableOpacity style={styles.touchable}
          onPress={this.gotoFetch}>

          <Text style={styles.textStyle}>FETCH API</Text>
        </TouchableOpacity>
        <View style={styles.flatList}>
          <FlatList
            data={this.state.dataSource}
            keyExtractor={(item, index) => index.toString()}
            ItemSeparatorComponent={this.FlatListItemSeparator}
            renderItem={({ item }) => {
              return (
                <Text style={styles.textStyle} >
                  {item.title}
                </Text>
              )
            }}
          />
        </View>
      </View>
    );
  }
};

export default App;

![screenshot-1580454074311](https://user-images.githubusercontent.com/4736998/73518938-a28f4b00-4425-11ea-9b70-c9fe30043514.jpg)

**Comment by mattdyoung** [comment]
Hi @SanjanaTailor 

What version of bugsnag-js are you using? This potentially sounds similar to an issue we've already fixed in v6.5.1:
https://github.com/bugsnag/bugsnag-js/issues/700

**Comment by SanjanaTailor** [comment]
@mattdyoung : I have not used bugsnag-js in current project. I am using it in expo directory.
Above all information mentioned and JS code too attached.

**Comment by mattdyoung** [comment]
@SanjanaTailor 
You've raised this as an issue with bugsnag-js. If you're not using bugsnag-js in your project I don't think there's any issue for the maintainers of bugsnag-js to resolve here.

If you are using bugsnag-js can you provide a reproducible example of the issue bugsnag-js is causing using the latest version v6.5.1.

**Comment by lc3t35** [comment]
Please reopen, we need to know what is the correct version of @react-native-community/netinfo that can be used with sdk35 too

```
@react-native-community/netinfo - expected version range: ~3.2.1 - actual version installed: ^5.5.1

@react-native-community/netinfo - expected version range: ~3.2.1 - actual version installed: 4.6.2

```
Both crash with `RNCNetInfo.getCurrentState got 3 arguments, expected 2.`.

**Comment by phillipsam** [comment]
Hi @lc3t35 - if you have a React Native project, we would recommend using our React Native notifier: https://github.com/bugsnag/bugsnag-react-native

Are you currently using bugsnag-js in your project? what version of bugsnag-js are you using?

**Comment by lc3t35** [comment]
I'm using expo sdk35 with "@bugsnag/expo": "6.4.1" for dev and  "bugsnag-react-native": "^2.23.2" for production.

**Comment by xander-jones** [comment]
Hey @lc3t35, the `bugsnag-react-native` library should not be used with Expo apps. Additionally, a fix was released that fixes an issue that sound exactly like this. This was released in [v6.5.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.5.1) of our `bugsnag-js` library. Can you please try a version that is at least v6.5.1 to see if the issue persists?

**Comment by lc3t35** [comment]
Yes as ejected Expo app, I use bugsnag-react-native ("bugsnag-react-native": "^2.23.6",)
But for staging/dev, I would like to use https://docs.bugsnag.com/platforms/react-native/expo/ too. What do you suggest ?
I had to remove bugsnag-react-native and @bugsnag/expo, so I can work on my project, I can stay stuck ... QA is waiting for updates.... without error catching then...
I expect to update to sdk36 soon, so I'll check again.

**Comment by mattdyoung** [comment]
@lc3t35 Have you confirmed that you still see this issue with the latest @bugsnag/expo which includes the fix @xander-jones refers to?
https://github.com/bugsnag/bugsnag-js/releases

**Comment by Ashwini-ap** [comment]
installing version 3.2.1 worked for me
